### ISSUE TITLE
Smallest size for a micro harmonic drive

### ISSUE THREAD

**Issue by JobBoozer** [robotology/whole-body-controllers#148]
Online, I saw this [micro harmonic drive](https://ukharmonicdrives.com/harmonic-drive-system/) that is highly recommended by specialists. I wonder if it’s the standard size or if there are others of its kind that are smaller. Could someone tell me about the smallest size of a micro harmonic drive? I’d appreciate photos too. Thanks!

**Comment by gabrielenava** [comment]
Sorry @JobBoozer, this type of question is out of topic in this repo. You may try to ask your question in another repo, such as https://github.com/robotology/community

closing!
