### ISSUE TITLE
Rename the repo?

### ISSUE THREAD

**Issue by traversaro** [robotology/whole-body-controllers#17]
The custom names of repository in the robotology organization are all lowercase, and with dash separating the names.

**Comment by gabrielenava** [comment]
It seems to me there are a couple of exceptions, e.g. https://github.com/robotology-playground/ftShoe_calibration, https://github.com/robotology-playground/WBI-Toolbox-controllers. Also this repo is in `robotology-playground`, not `robotology`. Apart from this, fine for me to rename it.

**Comment by traversaro** [comment]
If we use it in day-to-day activities, we should move it to robotology. robotology-playground is meant only for initial testing (hence the name).
