### ISSUE TITLE
Release the controllers with WB-Toolbox 3 support

### ISSUE THREAD

**Issue by diegoferigo** [robotology/whole-body-controllers#19]
Following https://github.com/robotology/QA/issues/279 and https://github.com/robotology-playground/whole-body-controllers/issues/5, the controllers stored in the `WBT3` branch can be merged if they're ready.

**Comment by gabrielenava** [comment]
This has been addressed with [this commit](https://github.com/robotology-playground/whole-body-controllers/commit/ebafdb4c8dc5a1f5020c76538c6da26ff7d46335). Closing.
