### ISSUE TITLE
Check if the Simulink required integration step is respected 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#38]
In view of https://github.com/robotology/wb-toolbox/issues/160, it seems that there might be an issue with the Simulink gui that impairs the achievement of the desired integration step.

As first thing, we need to verify if there are differences between running the standard demos (Yoga, standup) from command line or from the Simulink gui. 

@FabioBergonti if you already implemented a piece of code that allow to verify if the Simulink integration time is respected, can you please add it to this issue? I will then proceed to integrate it inside all the models.

**Comment by FabioBergonti** [comment]
Here what I did
I've added this block in my simulink model
![image](https://user-images.githubusercontent.com/38210073/45106224-6c697100-b136-11e8-994b-09b3fd24ed7d.png)
Then I evaluate `YARP_time0`
``` matlab
YARP_time0 = YARP_time.signals.values - YARP_time.signals.values(1);
```
After that some plots
#### Yarp Time VS simulink time
``` matlab
figure
hold on
plot(YARP_time0,0:length(YARP_time0)-1,'o')
plot(tout,0:length(tout)-1,'o-')
xlabel('Time [s]')
ylabel('Iteration')
grid on
legend('Yarp Time','Simulink Time')
```
![fig](https://user-images.githubusercontent.com/38210073/44842047-1e8bcf00-ac45-11e8-8dd4-df023cc5e710.png)

#### Delta Yarp Time
``` matlab
figure
plot(tout(1:end-1),diff(YARP_time0),'.-')
ylabel('Diff(Yarp Time) [s]')
xlabel('Absolute time [s]')
```
![fig2](https://user-images.githubusercontent.com/38210073/44913014-45710080-ad2c-11e8-8652-cd08344ef21d.png)

#### Distance between huge Delta Yarp Time
``` matlab
figure
Acc=diff(YARP_time0);
plot(diff(YARP_time0(Acc>0.018)),'.-')
ylabel('Distance [s]')
```
![fig2](https://user-images.githubusercontent.com/38210073/44913707-70f4ea80-ad2e-11e8-876f-bf7690beb951.png)

**Comment by gabrielenava** [comment]
Thanks @FabioBergonti! I added the checks in both the `Yoga` and `standup` models with [this commit](https://github.com/robotology/whole-body-controllers/commit/cb770c073f478f83d808a15d98b0ee1deed72c3e)

**Comment by gabrielenava** [comment]
I tested the Yoga++ demo on `iCubGenova02`, both from the Simulink GUI and from command line. As you can see, I got the same results @FabioBergonti already had for the jumping demo:

**From Simulink GUI, Yarp Time Vs. Simulink Time**

![screenshot from 2018-09-14 15-00-20](https://user-images.githubusercontent.com/12396934/45551801-45462a00-b82f-11e8-91c7-ba87ac5fa0e5.png)

Looking closer:

![screenshot from 2018-09-14 15-00-46](https://user-images.githubusercontent.com/12396934/45551800-45462a00-b82f-11e8-871b-487d0d5ba0f3.png)

The issue disappeared when running the Simulink model from command line:

**From Matlab command line, Yarp Time Vs. Simulink Time**

![screenshot from 2018-09-14 14-58-57](https://user-images.githubusercontent.com/12396934/45551802-45462a00-b82f-11e8-84b9-1ae900445538.png)

![screenshot from 2018-09-14 14-57-29](https://user-images.githubusercontent.com/12396934/45551803-45462a00-b82f-11e8-91e4-97282f2b9300.png)
 
I perceived the demo was also qualitatively different (faster) when launching it from the command line. Therefore I close this issue. The default method for running Simulink controller will become to launch the controllers from command line.

**Comment by yeshasvitirupachuri** [comment]
@venusPasandi FYI
