### ISSUE TITLE
Update all models to launch Simulink from command line

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#39]
In view of https://github.com/robotology/wb-toolbox/issues/160 and https://github.com/robotology/whole-body-controllers/issues/38, it is necessary to modify all the startup procedure of the Simulink controllers. The idea is to create a Matlab function named `startTorqueBalancingxxx.m` and the open a (static) gui that can handle the Simulink model without opening it.

**Comment by traversaro** [comment]
As you may know, there is no guarantee that this new way of launching the controllers will not stop working in new versions of MATLAB, depending on how the (unknown) internal details of MATLAB change. For this reason I think it would be ideal if there is a way to always inspect the discrepancy between the real time and the simulation time, eventually printing a warning/error or stopping if the maximum delay is reached. This will ensure that they will be no regression w.r.t. to this in the future.

**Comment by gabrielenava** [comment]
I agree. I will also include a warning or error

**Comment by gabrielenava** [comment]
I've found this example: https://www.mathworks.com/matlabcentral/answers/97557-is-it-possible-to-start-and-stop-a-simulink-simulation-from-inside-a-gui I will try to follow this procedure.

**Comment by gabrielenava** [comment]
Another interesting review of 3 different methods: https://blogs.mathworks.com/pick/2012/06/01/use-matlab-guis-with-simulink-models/

**Comment by gabrielenava** [comment]
A first prototype of the GUI have been created in [this branch](https://github.com/robotology/whole-body-controllers/tree/noSimulinkGui). There are still a couple of things I want to solve before merging in `master`, but I already tested the GUI on `iCubGenova02`. These are the results:


**Yoga ++, from Simulink GUI**

![screenshot from 2018-09-20 13-51-04](https://user-images.githubusercontent.com/12396934/45816842-21765e80-bcdd-11e8-820d-536c7197e465.png)

![screenshot from 2018-09-20 13-47-42](https://user-images.githubusercontent.com/12396934/45816843-220ef500-bcdd-11e8-93e3-3c2c60a90af1.png)

The problem is clearly present. 

**Yoga ++, from the new static GUI**

![screenshot from 2018-09-20 13-52-22](https://user-images.githubusercontent.com/12396934/45816861-305d1100-bcdd-11e8-8229-2f633bbf31dc.png)
![screenshot from 2018-09-20 13-52-00](https://user-images.githubusercontent.com/12396934/45816862-305d1100-bcdd-11e8-9bc3-29d2cfe21fdf.png)

By running Simulink with the new static GUI, the problem is solved and the difference between two time steps is always closed to 0.01 s. A similar result is obtained by running Simulink from command line:

**Yoga ++, from command line**

![screenshot from 2018-09-20 13-53-41](https://user-images.githubusercontent.com/12396934/45817291-88484780-bcde-11e8-8ab4-2896ff0ceea8.png)
![screenshot from 2018-09-20 13-53-27](https://user-images.githubusercontent.com/12396934/45817292-88e0de00-bcde-11e8-8509-79e5720f101e.png)


So, it seems the new GUI works! Here is a picture of how it looks like:

![screenshot from 2018-09-20 13-52-41](https://user-images.githubusercontent.com/12396934/45817312-9bf3ae00-bcde-11e8-93e3-bb1ed1bbd2ba.png)

**Comment by gabrielenava** [comment]
The [PR](https://github.com/robotology/whole-body-controllers/pull/42) is ready to be tested on the robot. Closing this issue, as the troubleshooting from now on will be done inside the PR.

Concerning the GUI, at this stage it has been added to the Yoga demo only. After testing it on the real robot, we may discuss if adding it also to the `standup` and `impedance` controllers in a future release.
