### ISSUE TITLE
Shall we add the harmonic drives inertia in the motors reflected inertia

### ISSUE THREAD

**Issue by FabioBergonti** [robotology/whole-body-controllers#49]
What do you think on adding the inertia of the harmonic drives?
From the [datasheet](https://harmonicdrive.de/mage/media//catalog/category/2014_11_ED_1019659_CSD-2A.pdf) I saw their inertia and is about $0.054*10^{-4} kg m^2$ (this is the mass moment of inertia of the gearing with respect to the input)
The dimension are not so different from the motors inertia

**Comment by gabrielenava** [comment]
It makes sense to me!

**Comment by traversaro** [comment]
![hd-1](https://user-images.githubusercontent.com/1857049/46728384-04e99880-cc83-11e8-86fb-831852ab6531.png)

Sorry for the italian.  : ) 
We had exactly the same discussion with @DanielePucci and @fiorisi , and we agreed that it make sense to include inertia of the part of the harmonic drive that is coupled with the motor shaft in the reflected inertias, as their order of magnitude is similar.

**Comment by traversaro** [comment]
cc @triccyx given that was apparently the one that sparked the discussion

**Comment by FabioBergonti** [comment]
Here a cross section of an harmonic drive
![image](https://user-images.githubusercontent.com/38210073/46728733-c1dbf500-cc83-11e8-94c9-4b7e1a897c43.png)
1. input shaft
2. wave generator
3. flexspline
4. circular spline
5. output shaft
6. housing

We have to add **only**  the inertia of the components (1) and (2), (all the rotating components before the flexspline)

**Comment by gabrielenava** [comment]
According to [this document](https://harmonicdrive.de/mage/media//catalog/category/2014_11_ED_1019659_CSD-2A.pdf) and looking at the following lines:

![screenshot from 2018-10-10 12-07-04](https://user-images.githubusercontent.com/12396934/46731585-5e55c580-cc8b-11e8-8f5c-fcfc237a0831.png)
![screenshot from 2018-10-10 12-06-21](https://user-images.githubusercontent.com/12396934/46731586-5e55c580-cc8b-11e8-9ab4-31a05bc70a46.png)

 it seems to me that for  the `CSD-17-2A` series the inertia value is $0.054*10^{-4} kg m^2$  that is the one that also  @FabioBergonti  suggested. I added it to the motors reflected inertia with this [PR](https://github.com/robotology/whole-body-controllers/pull/42). Waiting for testing it on the robot.

**Comment by gabrielenava** [comment]
The [PR](https://github.com/robotology/whole-body-controllers/pull/42) is ready to be tested on the robot. Closing this issue, as the troubleshooting from now on will be done inside the PR.

**Comment by DanielePucci** [comment]
Very well done guys. Thanks a lot

**Comment by traversaro** [comment]
Related Pinocchio issue: https://github.com/stack-of-tasks/pinocchio/issues/440 .
