### ISSUE TITLE
[WARNING]: WBC library of matlab functions will be transformed into a package in the future release

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#52]
In the current `master` branch, there is a [library](https://github.com/robotology/whole-body-controllers/tree/master/library/matlab) of matlab utility functions that are used by the controllers. However, we have other controllers in other github organizations, including [matlab-simulators](https://github.com/gabrielenava/matlab-multi-body-sim) that use local copies of these functions. I decided to convert this library in a [package](https://it.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html) in order to:

-  avoid to duplicate the `library` in several repositories;
-  allow to permanently add the `library` to the Matlab path. If I don't use the package, it may be difficult to understand which function is used in case there are functions with the same name in other folders in the path (there may be random failures, e.g. imagine you have your local version of the `skew` function in your local path. If for some reason the path to your local version of `skew` is not loaded, and the `library` of whole-body-controllers is in the Matlab path, your code may run anyways, but unexpected results may occur.

The modification has been implemented and tested  in this [PR](https://github.com/robotology/whole-body-controllers/pull/42). When it will be merged into `master`, all the standard demos (`yoga`, `standup`, `impedance`) should **work as before**.  All other not officially supported demos can  work as before as well, provided that the user **adds the prefix `wbc.` to the name of all the functions of the `library` when there is a call to these functions.** E.g.:

```

function [ ] = myRandomFunction ()

   % call to one of the functions in the library (add wbc.)
   [outputs] = wbc.nameOfFunctionInsideTheLibrary(inputs)
end

```
cc @Yeshasvitvs @aikolina

**Comment by gabrielenava** [comment]
Closing. I sent an email.

**Comment by yeshasvitirupachuri** [comment]
@gabrielenava The PR link is broken.

**Comment by gabrielenava** [comment]
link restored, thanks!
