### ISSUE TITLE
Documentation update for release 2.5

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#55]
By adding notes and advices.

cc @aikolina

**Comment by aikolina** [comment]
After discussing with @gabrielenava, we made this list of possible topics to cover.

**Possible notes:**
- describe briefly the theory behind each controller (math + diagrams) and add reference for detailed description

**Possible advice:**
- describe how to tune the CoM and joints gains for the yoga demo
- describe how to tune the regularization parameters for the yoga demo

**Comment by gabrielenava** [comment]
Documentation fully updated. Closing the issue and opening the one for release `3.0`.
