### ISSUE TITLE
[Archived knowledge] Matlab crashes when opening Simulink scopes

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#59]
I had issues on Ubuntu 18.04 LTS with Matlab 2018a: very often, after running a Simulink simulation with Gazebo, Matlab crashes after trying to open a scope. 

I fixed the issue by running Matlab from terminal as follows:

```
matlab -softwareopengl

````

**Comment by traversaro** [comment]
Note that there are tipically better solution then running MATLAB with `-softwareopengl`, as this result in much slower 3D visualization, see https://github.com/robotology/robotology-superbuild/issues/953 for more details.
