### ISSUE TITLE
Avoid to recompile the model every time when using the static GUI

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/whole-body-controllers#82]
Often, we need to run the YOGA from the static GUI multiple times in a row without changing anything. It is ok to compile the first time, but maybe after pressing STOP we could save some time by letting the user press START without compiling.

**Comment by gabrielenava** [comment]
This logic was done because I was afraid about the possibility that the user starts the controller by mistake by clicking on the "start" button.

I think the best way is to add a check button. If it is checked, the user will not be forced to recompile the code.

So also the "safe" option (recompile every time before pressing start) is preserved.

**Comment by gabrielenava** [comment]
I've implemented this request: now the GUI also has a checkbox as follows:

![Screenshot from 2020-03-17 19-01-54](https://user-images.githubusercontent.com/12396934/76887966-5a1bd780-6883-11ea-8c66-bc9877cb79f1.png)

if you check it, the `start model` won't be disabled after stopping the simulation and therefore it will be possible to press it without the need of recompiling the model. I am currently performing a testing session before committing the changes, but it seems that the new logic is working fine and not conflicting with the previous workflow.

**Comment by gabrielenava** [comment]
The new GUI has been tested with all models. It worked fine.

Here is the commit: https://github.com/robotology/whole-body-controllers/commit/bdbf7fdb23600ba9bfa0cbb1b10b2b60daf8096b

Here the parts of the commit relevant for this issue:

https://github.com/robotology/whole-body-controllers/commit/bdbf7fdb23600ba9bfa0cbb1b10b2b60daf8096b#diff-a084b794bc0759e7a6b77810e01874f2L34

https://github.com/robotology/whole-body-controllers/commit/bdbf7fdb23600ba9bfa0cbb1b10b2b60daf8096b#diff-df3f36a01ac9190881e2927bae2bbb7fL152

**Comment by S-Dafarra** [comment]
Thanks!
