### ISSUE TITLE
Links in the wiki not working

### ISSUE THREAD

**Issue by lrapetti** [robotology/whole-body-controllers#85]
Most of the links in the wiki page https://github.com/robotology/whole-body-controllers/wiki/whole-body-controllers-documentation seem to be outdated or pointing to non existing pages (if I try to open the links I get the following error message: `You do not have permission to update this wiki.`)

**Comment by gabrielenava** [comment]
I tried, something strange happened. In my case, it opens a GUI for creating  a new wiki page instead of opening the links. I guess i broke something, I'll investigate the problem

**Comment by gabrielenava** [comment]
All links have been fixed. Closing.
