### ISSUE TITLE
Decide where to locate the Yoga retargeting code

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#86]
Options may be:

- separate repo

- inside `whole-body-controllers`

cc @DanielePucci

**Comment by gabrielenava** [comment]
cc @Yeshasvitvs @kouroshD

**Comment by yeshasvitirupachuri** [comment]
Considering that yoga retargeting will be a viable demo in the future, I vote for inside `whole-body-controllers` as I see it to be easier for maintaining in the future and be aligned with the recent updates on the yoga controller

**Comment by DanielePucci** [comment]
For me, `whole-body-controllers` seems a good choice

**Comment by gabrielenava** [comment]
@Yeshasvitvs @kouroshD feel free to fork `devel`, add the `yoga retargeting` and open a PR on `devel` for this issue.

**Comment by gabrielenava** [comment]
Closing as we decided the code location.
