### ISSUE TITLE
Switching between different demos in task-based controller is complicated

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#9]
The issue is that the MPC walking controller needs a port to have the blocking read activated:

![screenshot from 2018-01-18 16-33-31](https://user-images.githubusercontent.com/12396934/35105990-585e2148-fc6d-11e7-9838-58c84bc751ff.png)

but this is preventing the "example state machine" demo to start. If one removes the blocking read for testing the controller without MPC, then it is difficult to remember to activate the blocking read again.

**Comment by gabrielenava** [comment]
cc @S-Dafarra

**Comment by S-Dafarra** [comment]
Because we need a different ``mdl`` for each demo :rofl:

**Comment by gabrielenava** [comment]
But the `example state machine` is not supposed to be a demo, is thought as a feature for debugging controller-only related issues/tuning.

**Comment by S-Dafarra** [comment]
It is rather a test, which usually are in separate files. But a test to be fruitful needs to be applied to a "close to working" configuration, so we fall again on the issue https://github.com/robotology-playground/wholeBodyControllers/issues/7

**Comment by gabrielenava** [comment]
The [torqueWalkingMPC](https://github.com/robotology-playground/wholeBodyControllers/tree/master/controllers/torqueWalkingMPC) controller is becoming more and more `walking-specific`, hence we can close this issue. Conclusion: just use the walking controller for walking.
